#%RAML 1.0
title: hello_world

/hello_world:
  description: "simple hello world program"
  get:
    description: "hello world string"
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Hello World"
              }
      404:
        body:
          application/json:
            example: |
              {
                "message": "Route not found"
              }
          

    